language: php
sudo: required

before_script:
  - sudo apt-get install -y expat
  - composer install

script:
  - ./vendor/bin/jsonlint -q inventory.schema.json
  - xmlwf tests/data/*.xml
  - for i in `ls tests/data/*.xml`; do ./bin/convert $i; done
  - php vendor/bin/atoum -mcn 1 -bf tests/bootstrap.php -c tests/telemetry.php -d tests/Glpi/

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly
matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
